name: Test R Library

run-name: ${{ github.actor }} is testing R Library

on: [push, pull_request]:
  branches:
    - 'main'
    - 'setup-r-library'
  paths:
    - '1-resources/r-library/'

jobs:
  test-r-library:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./1-resources/r-library

    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - name: Check out repository to runner
        uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
          with:
            r-version: ${{ matrix.r-version }}
      - name: Install required packages
        run: |
          source("tests/test-install-dependencies.R")
        shell: Rscript {0}
      - name: Run tests
        run: |
          source("test/test-library.R")
        shell: Rscript {0}
